version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2283251
      MYSQL_DATABASE: shipyard1
      MYSQL_USER: root1
      MYSQL_PASSWORD: 2283251
    ports:
      - "3307:3306"  # Change the host port to 3307

  my-java-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shipyard1
      SPRING_DATASOURCE_USERNAME: root1
      SPRING_DATASOURCE_PASSWORD: 2283251
